### ISSUE TITLE
skeleton

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/srdataset#1]

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#5](https://github.com/h1alexbel/srdataset/issues/5) is still not solved.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.2`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.3`

**Comment by 0pdd** [comment]
@h1alexbel the only puzzle [#5](https://github.com/h1alexbel/srdataset/issues/5) is solved here.
